name: Python CI
on:
  push:
    branches:
      - main
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.2
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run tests
        run: python -B -m pytest